[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "build"
  environment = { NODE_VERSION =  "16.5.1" }
[dev]
  command = "vite dev"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"