[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION =  "16.5.1" }
[dev]
  command = "vite dev"

[functions]
  directory = "netlify/functions"
  node_bundler  = "esbuild"